gave the arch wiki a dark mode
archlinux/archwiki pull request #59
Opened 2022-10-12 17:54 UTC by killertofus

Please fix what you need to fix

2022-10-13 04:20 UTC, pierres commented
Instead of copying the extension into our project could you reference it with a git submodule? This makes maintenance a lot easier. See the CheckUser extension for example.

2022-10-13 09:36 UTC, nl6720 commented on LocalSettings.archlinux.org.php
> +
The `LocalSettings.archlinux.org.php` file wasn't [removed](https://github.com/archlinux/archwiki/commit/058c6cbd5b0eb24934afab5b34147a060920922b) without a reason. Even if you add it back, nothing will use it.

ArchWiki's `LocalSettings.php` is in the infrastructure repo: https://gitlab.archlinux.org/archlinux/infrastructure/-/blob/master/roles/archwiki/templates/LocalSettings.php.j2.

2022-10-13 20:39 UTC, killertofus commented
@nl6720 @pierres should be fixed

2022-10-14 18:19 UTC, lahwaacz commented
There are 2 submodules now: in `mediawiki-extensions-DarkMode` and `extensions/mediawiki-extensions-DarkMode`.

And `LocalSettings.php.j2` does not belong in this repo - it needs to be maintained in the [infrastructure repo](https://gitlab.archlinux.org/archlinux/infrastructure/).

Also please squash your commits in the end.

2022-10-18 06:27 UTC, nl6720 requested changes

2022-10-18 06:27 UTC, nl6720 commented on .gitmodules
> +	url = https://github.com/wikimedia/mediawiki-extensions-DarkMode
The git submodule branch needs to match the used mediawiki release.

```suggestion
[submodule "extensions/DarkMode"]
	path = extensions/DarkMode
	url = https://github.com/wikimedia/mediawiki-extensions-DarkMode.git
	branch = REL1_38
```


The submodule currently should be at commit `fe470966d18fa4749f9b92097052fcd031e3cad6`.

2022-10-19 05:54 UTC, nl6720 requested changes
The submodule is still not properly added.
It should be in `extensions/DarkMode` not `extensions/mediawiki-extensions-DarkMode` and at the latest commit of the `REL1_38` branch.

2022-10-20 04:27 UTC, killertofus reviewed
@nl6720 it is

2022-10-20 05:34 UTC, lahwaacz commented
@killertofus It's not only about the `.gitmodules` file, the diff shows:
```
extensions/mediawiki-extensions-DarkMode
 Submodule mediawiki-extensions-DarkMode added at b36d0f
```

2022-12-29 16:00 UTC, closed without merging