Fix padding and alignment for Vector 2022 in MediaWiki 1.40
archlinux/archwiki pull request #69
Opened 2023-10-04 15:03 UTC by nl6720

Remove left and right padding around `.mw-content-container` when the screen width is less than 1000px. "Small screens" need all the horizontal space they can get.

Align the header contents and language selector so that they do not extend too far and trigger horizontal scrolling.

If everything works as it should it should looks like this:

Before:
![Screenshot 2023-10-04 at 18-00-00 Installation guide - ArchWiki](https://github.com/archlinux/archwiki/assets/17086862/6ddbd4c8-543f-4e08-9150-0214a6ec2985)

After:
![Screenshot 2023-10-04 at 18-00-19 Installation guide - ArchWiki](https://github.com/archlinux/archwiki/assets/17086862/57b02b23-d861-47e3-8fa9-58dd181f401b)

/cc @lahwaacz  @christian-heusel

2023-10-04 15:25 UTC, christian-heusel requested changes
Something isnt right: 
![image](https://github.com/archlinux/archwiki/assets/26827864/f1339092-4506-456c-bcee-1fc74b11f8bd)

2023-10-04 15:29 UTC, nl6720 commented
@christian-heusel this PR shouldn't cause such breakage. Does _it_ work without this PR?

2023-10-04 15:35 UTC, nl6720 commented
Ah, I think I see the syntax error I made.

2023-10-04 15:49 UTC, christian-heusel requested changes
Search bar and hamburger item are borked before loggin in:
![image](https://github.com/archlinux/archwiki/assets/26827864/22222e4a-63a2-494c-acb5-91a3bc78dea6)

Once logged in it looks good:
![image](https://github.com/archlinux/archwiki/assets/26827864/0983c76d-11a8-4694-a26f-dbfc83171129)

2023-10-04 16:09 UTC, christian-heusel approved these changes
Full Size:
![image](https://github.com/archlinux/archwiki/assets/26827864/2456ddcf-f2e7-4e71-8b4d-ee7b91a5d979)

Half Screen:
![image](https://github.com/archlinux/archwiki/assets/26827864/9f96a011-dc58-40c2-a578-e163f56dc3cd)

Phone Size:
![image](https://github.com/archlinux/archwiki/assets/26827864/001cae87-7207-4e73-b841-7bbdd5939b36)

Looks alright to me 👍🏻

2023-10-04 20:35 UTC, lahwaacz commented
The layout does not look right on 980px width:

![Screen Shot 2023-10-04 at 22 02 26](https://github.com/archlinux/archwiki/assets/1289205/fe829990-72fd-4fd9-be54-c46f80868e8d)

This is because `.mw-content-container` has `max-width: 60em` and removing horizontal padding for `.mw-page-container` below 1000px width broke it for this size. I also propose to remove the side borders on `#content`, apply the horizontal padding to `.mw-footer` too and increase the padding to 1em:
```diff
diff --git a/extensions/ArchLinux/modules/skins/vector.less b/extensions/ArchLinux/modules/skins/vector.less
index f6b638b57..1df0ccb00 100644
--- a/extensions/ArchLinux/modules/skins/vector.less
+++ b/extensions/ArchLinux/modules/skins/vector.less
@@ -85,9 +85,9 @@ body.skin-vector-2022 {

   // keep padding as we are using a visual border
   @media screen {
-    .mw-body {
-      padding-left: 0.5em;
-      padding-right: 0.5em;
+    .mw-body, .mw-footer {
+      padding-left: 1em;
+      padding-right: 1em;
     }
     .mw-ui-icon-flush-left {
       margin-left: 0;
@@ -97,10 +97,20 @@ body.skin-vector-2022 {
     }
   }
   @media screen and (max-width: 999px) {
+    // move horizontal padding from .mw-page-container to .mw-body and .mw-footer
     .mw-page-container {
       padding-left: 0;
       padding-right: 0;
     }
+    // increase max-width from 60em to 100%
+    .mw-content-container {
+      max-width: 100%;
+    }
+    // .mw-page-container has no horizontal padding so the border is useless
+    #content {
+      border-left: 0;
+      border-right: 0;
+    }
   }

   // Fix to not hide the login menu
```

With this patch it looks like this:

![Screen Shot 2023-10-04 at 22 22 42](https://github.com/archlinux/archwiki/assets/1289205/2072fe46-6574-4569-8311-48bed465ca26)

2023-10-05 05:31 UTC, nl6720 commented
> The layout does not look right on 980px width:

I noticed this too, but I didn't want risk touching `max-width`.

> I also propose to remove the side borders on `#content`, apply the horizontal padding to `.mw-footer` too and increase the padding to 1em:

The borders can be seen in pages with large tables, so I'd keep them. And IMO 1em takes up too much space on small screens.

2023-10-05 06:05 UTC, lahwaacz commented
> I noticed this too, but I didn't want risk touching `max-width`.

The `max-width` is limited by the `@media` query, so there should be no harm.

> The borders can be seen in pages with large tables, so I'd keep them.

Doh...

> And IMO 1em takes up too much space on small screens.

I think 1em looks much better on large screens. MediaWiki's native vector had 1.5em padding on `.mw-page-container` so even 1em would be thinner.

2023-10-05 06:07 UTC, nl6720 commented
> I think 1em looks much better on large screens. MediaWiki's native vector had 1.5em padding on `.mw-page-container` so even 1em would be thinner.

We could use 0.5em on 999px and less.

2023-10-05 15:05 UTC, lahwaacz approved these changes
Thanks @nl6720, LGTM!

2023-10-06 18:08 UTC, lahwaacz commented on extensions/ArchLinux/modules/skins/vector.less
>    }
There should be a blank line for consistency:
```suggestion
  }

```

2023-10-07 11:17 UTC, christian-heusel approved these changes
Nice teamwork @lahwaacz @nl6720 ✅

2023-10-07 11:17 UTC, merged